# Generated by Django 4.1.4 on 2022-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('frequency_band', models.CharField(max_length=20)),
                ('internal_gain', models.SmallIntegerField()),
                ('external_gain', models.SmallIntegerField()),
                ('beamwidth', models.SmallIntegerField()),
                ('downtilt', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('technologies', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('downstream', models.FloatField()),
                ('upstream', models.FloatField()),
            ],
        ),
    ]
