# Generated by Django 4.1.7 on 2023-05-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50, null=True)),
                ('primary_contact_name', models.CharField(max_length=50)),
                ('primary_contact_phone1', models.CharField(max_length=20)),
                ('primary_contact_phone2', models.CharField(max_length=20, null=True)),
                ('secondary_contact_name', models.CharField(max_length=50, null=True)),
                ('secondary_contact_phone1', models.CharField(max_length=20, null=True)),
                ('secondary_contact_phone2', models.CharField(max_length=20, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('mac_address', models.CharField(max_length=12)),
                ('serial_number', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('lease_time', models.BigIntegerField(null=True)),
                ('ipv4_address', models.GenericIPAddressField(null=True)),
                ('ipv4_netmask', models.SmallIntegerField(default=24, null=True)),
                ('ipv4_pool', models.CharField(default='pppoe', max_length=50, null=True)),
                ('ipv6_prefix', models.GenericIPAddressField(null=True)),
                ('ipv6_pool', models.CharField(max_length=50, null=True)),
                ('routes', models.TextField(null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriberequipment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.servicepackage')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriberLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100, null=True)),
                ('address_city', models.CharField(max_length=50)),
                ('address_state', models.CharField(max_length=2)),
                ('address_postal_code', models.CharField(max_length=50)),
                ('address_country', models.CharField(max_length=2)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriberequipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriberlocation'),
        ),
        migrations.AddField(
            model_name='subscriberequipment',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribers.subscriber'),
        ),
    ]
